micronaut:
  application:
    name: greeting
datasources:
  default:
    url: jdbc:mariadb://localhost/mquartz
    username: mquartz
    password: mquartz
    driverClassName: org.mariadb.jdbc.Driver
jpa:
  default:
    entity-scan:
      packages: 'info.leadinglight'
    properties:
      hibernate:
        show_sql: true
job:
  enabled: true
  quartz:
    org:
      quartz:
        scheduler:
          skipUpdateCheck: true
          instanceName: DatabaseScheduler
          instanceId: NON_CLUSTERED
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          dataSource: quartzDataSource
          tablePrefix: QRTZ_
        dataSource:
          quartzDataSource:
            driver: org.mariadb.jdbc.Driver
            URL: jdbc:mariadb://localhost/mquartz
            user: mquartz
            password: mquartz
            maxConnections: 8
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5
