micronaut:
  application:
    name: server
datasources:
  # Replace with any database you are using. Can be H2.
  default:
    url: jdbc:h2:file:./h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
jpa:
  default:
    packages-to-scan:
      - 'info.leadinglight.micronaut.jobs'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      # Sub-folders with numbers in them will not get properly configured.
      # We need to call the H2 htwo instead. Probably issue with flyway.
      locations: classpath:dbase/htwo
